[package]
name = "vault"
version = "1.0.0"
authors = []

[addresses]
vault="0x8aad78aa9414aa2f697fafe528e1b041e30fe5005e85d15d14f22401f5228826"
aptos_std = "0x1"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.cdpContract]
local = './cdpContract'


[dependencies.AtmosAggregator]
local = './atmos_swap_interface/aggregator'


[dependencies.dexlyn_swap]
git = "https://github.com/DexlynLabs/dexlyn_swap_interface"
rev = "mainnet"
